apiVersion: v1
kind: Service
metadata:
  name: twitty-service
spec:
  selector:
    app: twitty
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: twitty
spec:
  selector:
    matchLabels:
      app: twitty
  replicas: 3
  template:
    metadata:
      labels:
        app: twitty
    spec:
      containers:
      - name: twitty
        image: glushko/twitty:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000