apiVersion: v1
kind: Namespace
metadata:
  name: twitty
---
apiVersion: v1
kind: Service
metadata:
  name: twitty-service
  namespace: twitty
  labels:
    app: twitty
    tier: frontend
spec:
  selector:
    app: twitty
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: twitty-frontend
  namespace: twitty
  labels:
    app: twitty
    tier: frontend
spec:
  selector:
    matchLabels:
      app: twitty
      tier: frontend
  replicas: 3
  template:
    metadata:
      namespace: twitty
      labels:
        app: twitty
        tier: frontend
    spec:
      containers:
      - name: twitty
        image: glushko/twitty:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        envFrom:
          - configMapRef:
              name: twitty-database-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: twitty-frontend-config
  namespace: twitty
  labels:
    app: twitty
    tier: frontend
data:
  DATABASE_URL: postgresql://twitty:hry6!9xWwjEw8CWecYuV4wCD@db:5432/twitty
  SQL_HOST: db
  SQL_PORT: "5432"
  DATABASE: twitty
---
apiVersion: v1
kind: Service
metadata:
  name: twitty-database-service
  namespace: twitty
  labels:
    app: twitty
    tier: database
spec:
  selector:
    app: twitty-database
    tier: database
  type: LoadBalancer
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: twitty-database
  namespace: twitty
  labels:
    app: twitty
    tier: database
spec:
  serviceName: postgresql-db-service
  selector:
    matchLabels:
      app: twitty-database
      tier: database
  replicas: 2
  template:
    metadata:
      labels:
        app: twitty-database
        tier: database
    spec:
      containers:
        - name: twitty-database
          image: postgres:latest
          volumeMounts:
            - name: database-storage
              mountPath: /data
          envFrom:
            - configMapRef:
                name: twitty-database-config
  volumeClaimTemplates:
    - metadata:
        name: database-storage
        namespace: twitty
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: twitty-database-config
  namespace: twitty
  labels:
    app: twitty-database
    tier: database
data:
  POSTGRES_USER: twitty
  POSTGRES_PASSWORD: hry6!9xWwjEw8CWecYuV4wCD
  POSTGRES_DB: twitty
  PGDATA: /data/pgdata
