version: '3.8'

services:
  web:
    command: ./serve_development.sh
    build:
      context: ./
      dockerfile: Dockerfile
      target: development
    ports:
      - 8080:8000
    volumes:
      - ./:/app/