version: '3.8'

services:
  web:
    command: ./serve_development.sh
    build:
      context: ./
      dockerfile: Dockerfile
      target: development
    ports:
      - 8080:8000
    volumes:
      - ./:/app/
    env_file:
      - ./.env.dev.web

  db:
    image: postgres:13-alpine
    volumes:
      - ./data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev.db